language: node_js
node_js: stable
sudo: required
dist: trusty

install: true # travis/yarn bug

branches:
  only: master

addons:
  packages:
    - unzip
    - google-chrome-stable

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
#  - export CHROME_BIN=chromium-browser
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

after_failure:
  - cat /home/travis/build/joumenharzli/angular-seed/npm-debug.log

# https://docs.travis-ci.com/user/caching/#Caching-directories-(Bundler%2C-dependencies)
#cache:
#  directories: node_modules

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    - os: linux
      node_js: "6"
      env: JOB=test:unit
    - os: linux
      node_js: "6"
      env: JOB=test:e2e
    - os: linux
      node_js: "6"
      env: JOB=build:dev
    - os: linux
      node_js: "6"
      env: JOB=build:prod
    - os: linux
      node_js: "6"
      env: JOB=build:rollup
    - os: linux
      node_js: "6"
      env: JOB=build:aot      

script:
  - npm run $JOB